apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api-app
  template:
    metadata:
      labels:
        app: user-api-app
    spec:
      containers:
        - name: user-api-app
          image: andreibuhnici/user_api_weather
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-app
spec:
  ports:
    - port: 8090
  selector:
    app: user-api-app