apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-capstone
  template:
    metadata:
      labels:
        app: api-capstone
    spec:
      containers:
        - name: api-capstone
          image: andreibuhnici/api_capstone
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-capstone
spec:
  ports:
    - port: 8080
  selector:
    app: api-capstone