apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password  
        - name: PMA_HOST
          value: "mysql"
        - name: PMA_PORT
          value: "3306"
        ports:
        - name: http
          containerPort: 80
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: phpmyadmin-service
# spec:
#   type: NodePort
#   selector:
#     app: phpmyadmin
#   ports:
#   - protocol: TCP
#     nodePort: 31008
#     port: 80
#     targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-069543ec2b62eea2b" # control plane security group
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80